version: "3"
services:
  redis-server :
    image: redis
    ports:
     - 6379:6379
    network_mode: "host"
    volumes:
      - ${PWD}/tmp/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: redis-server
    command: ["redis-server"]
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure